// <auto-generated />
using System;
using LibraryShopEntities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ShopApi.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20241101190449_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.Cart", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_carts");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.CartBook", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("BookAmount")
                        .HasColumnType("integer")
                        .HasColumnName("book_amount");

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cart_id");

                    b.HasKey("Id")
                        .HasName("pk_cart_books");

                    b.HasIndex("CartId")
                        .HasDatabaseName("ix_cart_books_cart_id");

                    b.ToTable("cart_books", (string)null);
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.Client", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("phone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_user_id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("delivery_address");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_method");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_time");

                    b.Property<int>("OrderAmount")
                        .HasColumnType("integer")
                        .HasColumnName("order_amount");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer")
                        .HasColumnName("order_status");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_orders_client_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.OrderBook", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("BookAmount")
                        .HasColumnType("integer")
                        .HasColumnName("book_amount");

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<decimal>("BookPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("book_price");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.HasKey("Id")
                        .HasName("pk_order_books");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_books_order_id");

                    b.ToTable("order_books", (string)null);
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.StockBookChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("ChangeAmount")
                        .HasColumnType("integer")
                        .HasColumnName("change_amount");

                    b.Property<int?>("StockBookOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_book_order_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_book_changes");

                    b.HasIndex("StockBookOrderId")
                        .HasDatabaseName("ix_stock_book_changes_stock_book_order_id");

                    b.ToTable("stock_book_changes", (string)null);
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.StockBookOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("TotalChangeAmount")
                        .HasColumnType("integer")
                        .HasColumnName("total_change_amount");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stock_book_orders");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_stock_book_orders_client_id");

                    b.ToTable("stock_book_orders", (string)null);
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.CartBook", b =>
                {
                    b.HasOne("LibraryShopEntities.Domain.Entities.Shop.Cart", "Cart")
                        .WithMany("Books")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_books_carts_cart_id");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.Order", b =>
                {
                    b.HasOne("LibraryShopEntities.Domain.Entities.Shop.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.OrderBook", b =>
                {
                    b.HasOne("LibraryShopEntities.Domain.Entities.Shop.Order", "Order")
                        .WithMany("OrderBooks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_books_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.StockBookChange", b =>
                {
                    b.HasOne("LibraryShopEntities.Domain.Entities.Shop.StockBookOrder", null)
                        .WithMany("StockBookChanges")
                        .HasForeignKey("StockBookOrderId")
                        .HasConstraintName("fk_stock_book_changes_stock_book_orders_stock_book_order_id");
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.StockBookOrder", b =>
                {
                    b.HasOne("LibraryShopEntities.Domain.Entities.Shop.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_book_orders_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.Cart", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.Order", b =>
                {
                    b.Navigation("OrderBooks");
                });

            modelBuilder.Entity("LibraryShopEntities.Domain.Entities.Shop.StockBookOrder", b =>
                {
                    b.Navigation("StockBookChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
