version: '3.4'

services:
  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;
      - ASPNETCORE_HTTP_PORTS=8080
      - EFCreateDatabase=${EFCreateDatabase}
      - ConnectionStrings__AuthenticationDb=${ConnectionStrings__AuthenticationDb}
      - AuthSettings__Key=${AuthSettings__Key}
      - AuthSettings__Audience=${AuthSettings__Audience}
      - AuthSettings__Issuer=${AuthSettings__Issuer}
      - AuthSettings__ExpiryInMinutes=${AuthSettings__ExpiryInMinutes}
      - AuthSettings__RefreshExpiryInDays=${AuthSettings__RefreshExpiryInDays}
      - MaxPaginationPageSize=${MaxPaginationPageSize}
      - Auth__GoogleOAuth__ClientId=${Auth__GoogleOAuth__ClientId}
      - Auth__GoogleOAuth__ClientSecret=${Auth__GoogleOAuth__ClientSecret}
      - Auth__GoogleOAuth__Scope=${Auth__GoogleOAuth__Scope}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  libraryapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;
      - ASPNETCORE_HTTP_PORTS=8080
      - EFCreateDatabase=${EFCreateDatabase}
      - ConnectionStrings__LibraryDb=${ConnectionStrings__LibraryShopDb}
      - AuthSettings__Key=${AuthSettings__Key}
      - AuthSettings__Audience=${AuthSettings__Audience}
      - AuthSettings__Issuer=${AuthSettings__Issuer}
      - AuthSettings__ExpiryInMinutes=${AuthSettings__ExpiryInMinutes}
      - MaxPaginationPageSize=${MaxPaginationPageSize}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  shopapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;
      - ASPNETCORE_HTTP_PORTS=8080
      - EFCreateDatabase=${EFCreateDatabase}
      - ConnectionStrings__ShopDb=${ConnectionStrings__LibraryShopDb}
      - AuthSettings__Key=${AuthSettings__Key}
      - AuthSettings__Audience=${AuthSettings__Audience}
      - AuthSettings__Issuer=${AuthSettings__Issuer}
      - AuthSettings__ExpiryInMinutes=${AuthSettings__ExpiryInMinutes}
      - Shop__MaxOrderAmount=${Shop__MaxOrderAmount}
      - MaxPaginationPageSize=${MaxPaginationPageSize}
      - Chat__BotUrl=${ApiGateway}
      - LibraryApiUrl=${ApiGateway}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;https://+:8081;
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CertificatePassword}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx
      - AuthSettings__Key=${AuthSettings__Key}
      - AuthSettings__Audience=${AuthSettings__Audience}
      - AuthSettings__Issuer=${AuthSettings__Issuer}
      - AuthSettings__ExpiryInMinutes=${AuthSettings__ExpiryInMinutes}
      - AllowedCORSOrigins=${AllowedCORSOrigins}
      - UseCORS=${UseCORS}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
