version: '3.4'

services:
  userapi:
    container_name: elibrary-user-api
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    ports: 
      - 7130:8081
    networks:
    - backend-net

  libraryapi:
    container_name: elibrary-library-api
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: LibraryApi/Dockerfile
    ports: 
      - 7131:8081
    networks:
    - backend-net

  shopapi:
    container_name: elibrary-shop-api
    image: ${DOCKER_REGISTRY-}shopapi
    build:
      context: .
      dockerfile: ShopApi/Dockerfile
    ports: 
      - 7132:8081
    networks:
      - backend-net

networks:
  backend-net:
