#API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elibrary-apigateway
  labels:
    app: elibrary-apigateway
  annotations:
    resources.limits/memory: "512Mi"
    resources.limits/cpu: "500m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elibrary-apigateway
  template:
    metadata:
      labels:
        app: elibrary-apigateway
    spec:
      containers:
        - name: elibrary-apigateway
          image: tegto/elibrary-apigateway:dev
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: elibrary-config
            - secretRef:
                name: elibrary-secret
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  type: NodePort
  selector:
    app: elibrary-apigateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
---
#User API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elibrary-user-api
  labels:
    app: elibrary-user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elibrary-user-api
  template:
    metadata:
      labels:
        app: elibrary-user-api
    spec:
      containers:
        - name: elibrary-user-api
          image: tegto/elibrary-userapi:dev
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: elibrary-config
            - secretRef:
                name: elibrary-secret
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: userapi
spec:
  selector:
    app: elibrary-user-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
#Library API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elibrary-library-api
  labels:
    app: elibrary-library-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elibrary-library-api
  template:
    metadata:
      labels:
        app: elibrary-library-api
    spec:
      containers:
        - name: elibrary-library-api
          image: tegto/elibrary-libraryapi:dev
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: elibrary-config
            - secretRef:
                name: elibrary-secret
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: libraryapi
spec:
  selector:
    app: elibrary-library-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
#Shop API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elibrary-shop-api
  labels:
    app: elibrary-shop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elibrary-shop-api
  template:
    metadata:
      labels:
        app: elibrary-shop-api
    spec:
      containers:
        - name: elibrary-shop-api
          image: tegto/elibrary-shopapi:dev
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: elibrary-config
            - secretRef:
                name: elibrary-secret
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: shopapi
spec:
  selector:
    app: elibrary-shop-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---

