apiVersion: v1
kind: ConfigMap
metadata:
  name: elibrary-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080;"
  ASPNETCORE_HTTP_PORTS: "8080"
  EFCreateDatabase: "true"
  MaxPaginationPageSize: "99"
