apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elibrary-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elibrary-db
  labels:
    app: elibrary-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elibrary-db
  template:
    metadata:
      labels:
        app: elibrary-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: elibrary-db
          image: pgvector/pgvector:pg16
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: elibrary-db-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: elibrary-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: elibrary-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elibrary-secret
                  key: POSTGRES_PASSWORD
      volumes:
        - name: elibrary-db-data
          persistentVolumeClaim:
            claimName: elibrary-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elibrary-db-service
spec:
  type: NodePort
  selector:
    app: elibrary-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30007
