apiVersion: apps/v1
kind: Deployment
metadata:
  name: elibrary-frontend
  labels:
    app: elibrary-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elibrary-frontend
  template:
    metadata:
      labels:
        app: elibrary-frontend
    spec:
      containers:
        - name: elibrary-frontend
          image: tegto/elibrary-frontend:dev
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: elibrary-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30009
