name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'src/ELibrary.Backend/**'
      - 'test/**'

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
        
      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: |
          dotnet restore src/ELibrary.Backend/Authentication/Authentication.csproj
          dotnet restore src/ELibrary.Backend/Shared/Shared.csproj
          dotnet restore src/ELibrary.Backend/LibraryApi/LibraryApi.csproj
          dotnet restore src/ELibrary.Backend/UserApi/UserApi.csproj
          dotnet restore test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/AuthenticationTests/AuthenticationTests.csproj
          dotnet restore test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/SharedTests/SharedTests.csproj
          dotnet restore test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/LibraryApiTests/LibraryApiTests.csproj
          dotnet restore test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/UserApiTests/UserApiTests.csproj

      - name: Build projects
        run: |
          dotnet build src/ELibrary.Backend/Authentication/Authentication.csproj --configuration Release
          dotnet build src/ELibrary.Backend/Shared/Shared.csproj --configuration Release
          dotnet build src/ELibrary.Backend/LibraryApi/LibraryApi.csproj --configuration Release
          dotnet build src/ELibrary.Backend/UserApi/UserApi.csproj --configuration Release
          dotnet build test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/AuthenticationTests/AuthenticationTests.csproj --configuration Release
          dotnet build test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/SharedTests/SharedTests.csproj --configuration Release
          dotnet build test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/LibraryApiTests/LibraryApiTests.csproj --configuration Release
          dotnet build test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/UserApiTests/UserApiTests.csproj --configuration Release

      - name: Run unit tests
        run: |
          dotnet test test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/AuthenticationTests/AuthenticationTests.csproj --verbosity normal --configuration Release
          dotnet test test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/SharedTests/SharedTests.csproj --verbosity normal --configuration Release
          dotnet test test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/LibraryApiTests/LibraryApiTests.csproj --verbosity normal --configuration Release
          dotnet test test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/UserApiTests/UserApiTests.csproj --verbosity normal --configuration Release

      - name: Check results
        run: |
          echo "Tests have been executed."
