name: Continuous Integration Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop-release
    paths:
      - "src/ELibrary.Frontend/**"
  pull_request:
    branches:
      - main
      - develop-release
    paths:
      - "src/ELibrary.Frontend/**"

env:
  NODE_VERSION: "20.x"

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install --force
        working-directory: src/ELibrary.Frontend

      - name: Run tests with coverage
        run: npm run test:ci -- --code-coverage
        working-directory: src/ELibrary.Frontend

      - name: Upload code coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: src/ELibrary.Frontend/coverage

      - name: Install Java 17 for SonarCloud
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install SonarCloud Scanner
        run: npm install -g sonar-scanner

      - name: Run SonarCloud Analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.sources=src/ELibrary.Frontend/src \
            -Dsonar.tests=src/ELibrary.Frontend/src \
            -Dsonar.test.inclusions="src/ELibrary.Frontend/src/**/*.spec.ts" \
            -Dsonar.javascript.lcov.reportPaths=src/ELibrary.Frontend/coverage/lcov.info \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.branch.name=${{ github.ref_name }}

      - name: Build Angular Project
        run: npm run build -- --configuration production
        working-directory: src/ELibrary.Frontend

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: src/ELibrary.Frontend/dist
