name: Continuous Integration Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop-release-1
    paths:
      - 'src/ELibrary.Backend/**'
      - 'test/**'
  pull_request:
    branches:
      - main
      - develop-release-1
    paths:
      - 'src/ELibrary.Backend/**'
      - 'test/**'

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
        
      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: |
          dotnet restore src/ELibrary.Backend/ELibrary.Backend.sln

      - name: Build projects
        run: |
          dotnet build src/ELibrary.Backend/ELibrary.Backend.sln

      - name: Run unit tests
        run: |
          dotnet test src/ELibrary.Backend/ELibrary.Backend.sln

      - name: Check results
        run: |
          echo "Tests have been executed."
