name: Continuous Integration Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/ELibrary.Frontend/**'

jobs:
  build_and_test_job:
    runs-on: ubuntu-latest
    name: Build and Test Job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
        working-directory: src/ELibrary.Frontend

      - name: Run tests
        run: npm run test:ci
        working-directory: src/ELibrary.Frontend