name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/ELibrary.Backend/**'

env:
  DOTNET_VERSION: '7.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api:
          - name: "User API"
            path: "UserApi"
            azure_app_name: "elibrary-user-api-germanywestcentral-001"
            publish_secret: USER_API_PUBLISH_SECRET
          - name: "Library API"
            path: "LibraryApi"
            azure_app_name: "elibrary-library-api-germanywestcentral-001"
            publish_secret: LIBRARY_API_PUBLISH_SECRET

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache .NET packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: |
        dotnet restore src/ELibrary.Backend/Authentication/Authentication.csproj
        dotnet restore src/ELibrary.Backend/Shared/Shared.csproj
        dotnet restore src/ELibrary.Backend/LibraryApi/LibraryApi.csproj
        dotnet restore src/ELibrary.Backend/UserApi/UserApi.csproj
        dotnet restore test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/AuthenticationTests/AuthenticationTests.csproj
        dotnet restore test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/SharedTests/SharedTests.csproj
        dotnet restore test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/LibraryApiTests/LibraryApiTests.csproj
        dotnet restore test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/UserApiTests/UserApiTests.csproj

    - name: Build projects
      run: |
        dotnet build src/ELibrary.Backend/Authentication/Authentication.csproj --configuration Release --no-restore
        dotnet build src/ELibrary.Backend/Shared/Shared.csproj --configuration Release --no-restore
        dotnet build src/ELibrary.Backend/LibraryApi/LibraryApi.csproj --configuration Release --no-restore
        dotnet build src/ELibrary.Backend/UserApi/UserApi.csproj --configuration Release --no-restore
        dotnet build test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/AuthenticationTests/AuthenticationTests.csproj --configuration Release --no-restore
        dotnet build test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/SharedTests/SharedTests.csproj --configuration Release --no-restore
        dotnet build test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/LibraryApiTests/LibraryApiTests.csproj --configuration Release --no-restore
        dotnet build test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/UserApiTests/UserApiTests.csproj --configuration Release --no-restore

    - name: Run unit tests
      run: |
        dotnet test test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/AuthenticationTests/AuthenticationTests.csproj --verbosity normal --configuration Release
        dotnet test test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/SharedTests/SharedTests.csproj --verbosity normal --configuration Release
        dotnet test test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/LibraryApiTests/LibraryApiTests.csproj --verbosity normal --configuration Release
        dotnet test test/ELibrary.UnitTests/ELibrary.UnitTests.Backend/UserApiTests/UserApiTests.csproj --verbosity normal --configuration Release

    - name: Publish
      run: dotnet publish src/ELibrary.Backend/${{ matrix.api.path }} --configuration Release --output ./src/ELibrary.Backend/${{ matrix.api.path }}/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ matrix.api.azure_app_name }}
        slot-name: 'production'
        publish-profile: ${{ secrets[matrix.api.publish_secret] }}
        package: ./src/ELibrary.Backend/${{ matrix.api.path }}/publish
